"""remove_role_column_from_tenant_account

Revision ID: 11be00ec061b
Revises: 1f863ef7c2f0
Create Date: 2025-10-08 09:23:54.796051

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11be00ec061b'
down_revision = '1f863ef7c2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_account_joins', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_account_joins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=16), server_default=sa.text("'normal'::character varying"), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
