"""add_roles_and_permissions_table

Revision ID: 503162324a08
Revises: fd5f4d8ddae3
Create Date: 2025-10-03 14:59:41.696654

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503162324a08'
down_revision = 'fd5f4d8ddae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='module_pkey')
    )
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_index('module_name_idx', ['name'], unique=False)

    op.create_table('permissions',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sub_module_id', models.types.StringUUID(), nullable=True),
    sa.Column('is_superadmin_only', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='permission_pkey')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index('permission_code_idx', ['code'], unique=False)
        batch_op.create_index('permission_name_idx', ['name'], unique=False)
        batch_op.create_index('permission_sub_module_id_idx', ['sub_module_id'], unique=False)

    op.create_table('role_account_joins',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('account_id', models.types.StringUUID(), nullable=False),
    sa.Column('role_id', models.types.StringUUID(), nullable=False),
    sa.Column('created_by', models.types.StringUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='role_account_join_pkey'),
    sa.UniqueConstraint('account_id', 'role_id', name='unique_account_role')
    )
    with op.batch_alter_table('role_account_joins', schema=None) as batch_op:
        batch_op.create_index('role_account_join_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('role_account_join_role_id_idx', ['role_id'], unique=False)
        batch_op.create_index('role_account_join_tenant_id_idx', ['tenant_id'], unique=False)

    op.create_table('role_permission_joins',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('role_id', models.types.StringUUID(), nullable=False),
    sa.Column('permission_id', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='role_permission_join_pkey'),
    sa.UniqueConstraint('role_id', 'permission_id', name='unique_role_permission')
    )
    with op.batch_alter_table('role_permission_joins', schema=None) as batch_op:
        batch_op.create_index('role_permission_join_permission_id_idx', ['permission_id'], unique=False)
        batch_op.create_index('role_permission_join_role_id_idx', ['role_id'], unique=False)
        batch_op.create_index('role_permission_join_tenant_id_idx', ['tenant_id'], unique=False)

    op.create_table('roles',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('created_by', models.types.StringUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='role_pkey')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('role_name_idx', ['name'], unique=False)

    op.create_table('sub_modules',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('module_id', models.types.StringUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='sub_module_pkey')
    )
    with op.batch_alter_table('sub_modules', schema=None) as batch_op:
        batch_op.create_index('module_id_idx', ['module_id'], unique=False)
        batch_op.create_index('sub_module_name_idx', ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_modules', schema=None) as batch_op:
        batch_op.drop_index('sub_module_name_idx')
        batch_op.drop_index('module_id_idx')

    op.drop_table('sub_modules')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('role_name_idx')

    op.drop_table('roles')
    with op.batch_alter_table('role_permission_joins', schema=None) as batch_op:
        batch_op.drop_index('role_permission_join_tenant_id_idx')
        batch_op.drop_index('role_permission_join_role_id_idx')
        batch_op.drop_index('role_permission_join_permission_id_idx')

    op.drop_table('role_permission_joins')
    with op.batch_alter_table('role_account_joins', schema=None) as batch_op:
        batch_op.drop_index('role_account_join_tenant_id_idx')
        batch_op.drop_index('role_account_join_role_id_idx')
        batch_op.drop_index('role_account_join_account_id_idx')

    op.drop_table('role_account_joins')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index('permission_sub_module_id_idx')
        batch_op.drop_index('permission_name_idx')
        batch_op.drop_index('permission_code_idx')

    op.drop_table('permissions')
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index('module_name_idx')

    op.drop_table('modules')
    # ### end Alembic commands ###
