"""add_groups_and_binding_table

Revision ID: fd5f4d8ddae3
Revises: 68519ad5cd18
Create Date: 2025-10-03 14:56:06.570955

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5f4d8ddae3'
down_revision = '68519ad5cd18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_bindings',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=True),
    sa.Column('group_id', models.types.StringUUID(), nullable=True),
    sa.Column('target_id', models.types.StringUUID(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('created_by', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='group_binding_pkey')
    )
    with op.batch_alter_table('group_bindings', schema=None) as batch_op:
        batch_op.create_index('group_bind_group_id_idx', ['group_id'], unique=False)
        batch_op.create_index('group_bind_target_id_idx', ['target_id'], unique=False)
        batch_op.create_index('group_bind_type_idx', ['type'], unique=False)

    op.create_table('groups',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agency_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('created_by', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='group_pkey')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index('group_name_idx', ['name'], unique=False)

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_column('credential_status')

    with op.batch_alter_table('tag_bindings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtype', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_bindings', schema=None) as batch_op:
        batch_op.drop_column('subtype')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credential_status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True))

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index('group_name_idx')

    op.drop_table('groups')
    with op.batch_alter_table('group_bindings', schema=None) as batch_op:
        batch_op.drop_index('group_bind_type_idx')
        batch_op.drop_index('group_bind_target_id_idx')
        batch_op.drop_index('group_bind_group_id_idx')

    op.drop_table('group_bindings')
    # ### end Alembic commands ###
